import "./globals.css";
import { Inter, Rubik } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.variable}`}>{children}</body>
    </html>
  );
}
